<?php
// This file is automatically generated. Don't make manual changes as they will get overwritten when you republish your website.
$_SETTINGS = [
	"to"						=> "{to}",							// To Address
	"toAlt"						=> "{to-alt}",						// Additional Recipients
	"from"						=> "{from}",						// From Address
	"fromName"					=> "{from-name}",					// From Name
	"fromThem"					=> "{from-them}",					// Use Sender as From Address
	"fromThemReplyTo"			=> "{from-them-replyto}",			// Use Sender as Reply-To
	"fromNameThem"				=> "{from-name-them}",				// Use Sender Name as From Name
	"fromNameThemField"			=> "{from-name-them-field}",		// Name of the field(s) that can contain the Sender Name
	"template"					=> "{template}",					// Mail Template
	"dateFormat"				=> "{dateformat}",					// Date format
	"timeFormat"				=> "{timeformat}",					// Time format
	"autorespondSubjectPrefix"	=> "{autorespond-subjectprefix}",	// Autorespond Form Subject Prefix
	"autorespondSubject"		=> "{autorespond-subject}",			// Autorespond Custom Subject
	"autorespondTemplate"		=> "{autorespond-template}",		// Autorespond Template
	"rcp"						=> "{recaptcha}",					// Use reCAPTCHA
	"rcpVersion"				=> "{recaptcha-version}",			// reCAPTCHA Version
	"rcpScore"					=> "{recaptcha-score}",				// reCAPTCHA Score
	"rcpSecret"					=> "{recaptcha-secretkey}",			// reCAPTCHA Secret Key
	"smtp"						=> "{smtp}",						// Use SMTP
	"smtpDebug"					=> "{smtp-debug}",					// SMTP Debug
	"smtpHost"					=> "{smtp-host}",					// SMTP Host
	"smtpPort"					=> "{smtp-port}",					// SMTP Port
	"smtpSecure"				=> "{smtp-secure}",					// SMTP Use SSL/TLS (empty, ssl or tls)
	"smtpUsername"				=> "{smtp-username}",				// SMTP Username
	"smtpPassword"				=> "{smtp-password}",				// SMTP Password
	"attachmentsExtensions"		=> "{attachments-extensions}",		// File Extensions
	"attachmentsMimeTypes"		=> "{attachments-mimetypes}",		// Mime Types
	"allowedHTML"				=> "{allowedhtml}"					// Allowed HTML Tags (BB)
];
?>